### ISSUE TITLE
Can't find the dataset

### ISSUE THREAD

**Issue by udaykamal20** [HuCaoFighting/DVS-GraspingDataSet#1]
Hi,
I have read your paper and it's a very interesting dataset, indeed! Unfortunately, I can't access or find any link to download the dataset in this repository. Am I missing something?

**Comment by HuCaoFighting** [comment]
We have collected a new event-based grasping dataset. Both the new one and the old version will be public in the next few days.

**Comment by udaykamal20** [comment]
Thanks for your reply, really looking forward to it!

**Comment by yellow07200** [comment]
Hi, 
Can anyone tell me where I can find this interesting dataset?

**Comment by HuCaoFighting** [comment]
The dataset is published.
