### ISSUE TITLE
Raw event streams available?

### ISSUE THREAD

**Issue by jackd** [HuCaoFighting/DVS-GraspingDataSet#2]
Hi, I'm a researcher looking at learning methods for event streams and this work came up. I've downloaded the dataset but can only find images. Are the raw event streams available? Thanks in advance.

**Comment by HuCaoFighting** [comment]
Yes, because the raw event data is too big and I don't have enough cloud storage space to store it. Therefore, I can't share the raw event data right now.

**Comment by HuCaoFighting** [comment]
No more questions
